//
// Created by mikulec on 12/31/23.
//

#ifndef SERVER_MESSAGE_TYPES_H
#define SERVER_MESSAGE_TYPES_H

typedef enum server_message_type {
    CREATE_SERVER,
    KILL_SERVER,
    PORT_OCCUPIED,
    SERVER_CREATED,
    GAMES_ARE_RUNNING,
    SERVER_IS_OFF,
    STATISTICS,
    UNKNOWN,
    SUCCESS
} SERVER_MESSAGE_TYPE;

#endif //SERVER_MESSAGE_TYPES_H